---
title: National PPE Coalition
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  organizations:
    title: Organizations
    output: false
url: https://ppecoalition.com
plugins:
- jekyll-sitemap
- jekyll-seo-tag
sass:
  sass_dir: _sass
exclude:
- ".sass-cache/"
- ".jekyll-cache/"
- gemfiles/
- Gemfile
- Gemfile.lock
- node_modules/
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- README.md
include:
- _redirects
