---
title: C19 Coalition
timezone: UTC
collections:
  authors:
    title: Authors
    output: true
  health:
    title: Mental Health Resources
    output: false
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  organizations:
    title: Organizations
    output: false
url: https://c19coalition.org
plugins:
- jekyll-sitemap
- jekyll-seo-tag
sass:
  sass_dir: _sass
exclude:
- ".sass-cache/"
- ".jekyll-cache/"
- gemfiles/
- Gemfile
- Gemfile.lock
- node_modules/
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- README.md
include:
- _redirects
