# Warning: This file can be found at admin/config.yml or _data/cms.yml. Do not add _data/config.yml
# to the git repository, do not remove the file from the .gitignore file. For more details read
# the comments in _admin/copy-cms-data-file.rb

# Warning: This config drives the CMS UI available at /admin. The CMS persists changes against the git remote
# repository branch specified below. The default branch is setup against 'master' which is the production site.
# This means that even if you run a local branch, edits to master will be persisted on the 'master' remote branch (if pushed and merged).
# If you need to experiment with site content, either rename the branch in this config to something else.
# To work locally you can use the experimental netlify-cms proxy. First insall it:
#   npm install -g netlify-cms-proxy-server
# Then start it
#    npx netlify-cms-proxy-server
local_backend: true
backend:
  name: git-gateway
  branch: 'master'
media_folder: 'assets/uploads'
publish_mode: editorial_workflow
collections:
  - name: "blog"
    label: "Blog"
    folder: "_posts/"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Estimated Reading Time (x-y minutes read)", name: "reading_time", widget: "string" }
      - {
          label: "Author",
          name: "author",
          widget: "relation",
          collection: "authors",
          displayFields: [name],
          searchFields: [name],
          valueField: "name",
        }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Footer", name: "footer", widget: "markdown", required: false }
      - { label: "Thumbnail", name: "thumbnail", widget: "image", required: true }
      - { label: "Summary", name: "summary", widget: "markdown", required: true }
  - name: "authors"
    label: "Authors"
    folder: "_authors/"
    create: true
    editor:
      preview: false
    identifier_field: 'name'
    fields:
      - { label: "Full Name", name: "name", widget: "string" }
      - { label: "Position", name: "position", widget: "string" }
      - { label: "Favored social media profile URL", name: "social", widget: "string", required: false }
  - name: "health"
    label: "Mental Health Resources"
    folder: "_health/"
    create: true
    identifier_field: name
    editor:
      preview: false
    fields:
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'markdown', required: false }
      - label: 'Type'
        name: 'type'
        multiple: true
        widget: 'select'
        options:
          - { label: 'African American Community ', value: 'african-american' }
          - { label: 'Meditation', value: 'meditation' }
          - { label: 'Crisis Hotline', value: 'crisis-hotlines' }
          - { label: 'Frontline Worker', value: 'frontline-workers' }
          - { label: 'Therapist', value: 'therapist' }
          - { label: 'Virtual Therapy Offer', value: 'virtual-therapy' }
          - { label: 'Other', value: 'other' }
      - label: 'Top section of health page'
        default: 'no'
        name: 'top_health'
        widget: 'select'
        options:
          - { label: 'Yes', value: 'yes' }
          - { label: 'No', value: 'no' }
      - { label: 'URL', name: 'site_url', widget: 'string', required: false}
  - name: 'organization'
    label: 'Organization'
    folder: '_organizations/'
    create: true
    editor:
      preview: false
    identifier_field: 'name'
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'organization' }
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'markdown' }
      - label: 'Type'
        name: 'type'
        widget: 'select'
        multiple: true
        options:
          - { label: 'Need PPE', value: 'need-ppe' }
          - { label: 'Supply PPE', value: 'supply-ppe' }
          - { label: 'Connect Demand with Supply', value: 'connect-demand-with-supply' }
          - { label: 'Provide Funding', value: 'provide-funding' }
          - { label: 'Provide Data', value: 'provide-data' }
          - { label: 'Provide Resources for Makers', value: 'provide-resources-for-makers' }
          - { label: 'Provide Transportation & Logistics', value: 'provide-transportation-and-logistics' }
          - { label: 'Manufacture PPE & Other Equipment', value: 'manufacture-ppe-and-other-equipment' }
          - { label: 'Assist with Regulatory Issues', value: 'assist-with-regulatory-issues' }
          - { label: 'Develop New Technologies', value: 'develop-new-technologies' }
          - { label: 'Sell PPE to Consumers', value: 'sell-ppe-to-consumers' }
          - { label: 'Other', value: 'other' }
      - label: 'Structure'
        name: 'structure'
        widget: 'select'
        options:
          - { label: 'Government', value: 'government' }
          - { label: 'Corporate', value: 'corporate' }
          - { label: 'Individual', value: 'individual' }
          - { label: 'Nonprofit', value: 'nonprofit' }
          - { label: 'Volunteer', value: 'volunteer' }
          - { label: 'Other', value: 'other' }
      - label: 'Location'
        name: 'location'
        widget: 'select'
        options:
          - 'Nationwide'
          - 'Multinational'
          - 'Alaska'
          - "Alabama"
          - "Arkansas"
          - "American Samoa"
          - "Arizona"
          - "California"
          - "Colorado"
          - "Connecticut"
          - "District of Columbia"
          - "Delaware"
          - "Florida"
          - "Georgia"
          - "Guam"
          - "Hawaii"
          - "Iowa"
          - "Idaho"
          - "Illinois"
          - "Indiana"
          - "Kansas"
          - "Kentucky"
          - "Louisiana"
          - "Massachusetts"
          - "Maryland"
          - "Maine"
          - "Michigan"
          - "Minnesota"
          - "Missouri"
          - "Mississippi"
          - "Montana"
          - "North Carolina"
          - "North Dakota"
          - "Nebraska"
          - "New Hampshire"
          - "New Jersey"
          - "New Mexico"
          - "Nevada"
          - "New York"
          - "Ohio"
          - "Oklahoma"
          - "Oregon"
          - "Pennsylvania"
          - "Puerto Rico"
          - "Rhode Island"
          - "South Carolina"
          - "South Dakota"
          - "Tennessee"
          - "Texas"
          - "Utah"
          - "Virginia"
          - "Virgin Islands"
          - "Vermont"
          - "Washington"
          - "Wisconsin"
          - "West Virginia"
          - "Wyoming"
      - { label: 'Coalition Member', name: 'is_member', widget: 'boolean', default: false}
      - { label: 'On Home Page', name: 'show_on_home_page', widget: 'boolean', default: false, required: false}
      - { label: 'Only On Home Page', name: 'only_on_home_page', widget: 'boolean', default: false, required: false}
      - { label: 'URL', name: 'site_url', widget: 'string', required: false}
      - label: "Logo"
        name: "logo"
        widget: "image"
        required: false
      - label: "Contact"
        name: "contact"
        widget: "object"
        fields:
          - {label: "Name", name: "name", widget: "string", required: false}
          - {label: "Email", name: "email", widget: "string", required: false}
          - {label: "Phone", name: "phone", widget: "string", required: false}
        required: false
  - label: "Pages"
    name: "pages"
    editor:
      preview: false
    files:
      - label: "Donate"
        name: "donate"
        file: "pages/donate"
        fields:
          - {label: 'Layout', name: 'layout', widget: 'hidden', default: 'default' }
          - {label: Content, name: main, widget: markdown}
      - label: "Home Page"
        name: "home"
        file: "pages/index.html"
        fields:
          - {label: 'Layout', name: 'layout', widget: 'hidden', default: 'default' }
          - {label: Intro, name: intro, widget: markdown}
          - label: Section
            name: sections
            widget: list
            fields:
              - {label: Description, name: description, widget: markdown}
              - label: "Organizations"
                name: orgs
                widget: list
                fields:
                  - label: "Organization"
                    name: org_name
                    widget: relation
                    collection: organization
                    searchFields: ["name"]
                    valueField: name
                    displayFields: ["name"]
          - {label: Outro, name: outro, widget: markdown}
      - label: "Commitments Page"
        name: "commitments"
        file: "pages/commitments.html"
        fields:
          - {label: 'Layout', name: 'layout', widget: 'hidden', default: 'default' }
          - {label: Content, name: main, widget: markdown}
      - label: "PPE Orgs Page"
        name: "ppe-orgs"
        file: "pages/ppe-orgs.html"
        fields:
          - {label: 'Layout', name: 'layout', widget: 'hidden', default: 'default' }
          - {label: Content, name: main, widget: markdown}
