backend:
  name: git-gateway
  branch: 'feature/home-page-in-cms'
media_folder: 'assets/uploads'
collections:
  - name: 'organization'
    label: 'Organization'
    folder: '_organizations/'
    create: true
    editor:
      preview: false
    identifier_field: 'name'
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'organization' }
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'markdown' }
      - label: 'Type'
        name: 'type'
        widget: 'select'
        multiple: true
        options:
          - { label: 'Need PPE', value: 'need-ppe' }
          - { label: 'Supply PPE', value: 'supply-ppe' }
          - { label: 'Connect Demand with Supply', value: 'connect-demand-with-supply' }
          - { label: 'Provide Funding', value: 'provide-funding' }
          - { label: 'Provide Data', value: 'provide-data' }
          - { label: 'Provide Resources for Makers', value: 'provide-resources-for-makers' }
          - { label: 'Provide Transportation & Logistics', value: 'provide-transportation-and-logistics' }
          - { label: 'Manufacture PPE & Other Equipment', value: 'manufacture-ppe-and-other-equipment' }
          - { label: 'Assist with Regulatory Issues', value: 'assist-with-regulatory-issues' }
          - { label: 'Develop New Technologies', value: 'develop-new-technologies' }
          - { label: 'Sell PPE to Consumers', value: 'sell-ppe-to-consumers' }
          - { label: 'Other', value: 'other' }
      - label: 'Structure'
        name: 'structure'
        widget: 'select'
        options:
          - { label: 'Government', value: 'government' }
          - { label: 'Corporate', value: 'corporate' }
          - { label: 'Individual', value: 'individual' }
          - { label: 'Nonprofit', value: 'nonprofit' }
          - { label: 'Volunteer', value: 'volunteer' }
          - { label: 'Other', value: 'other' }
      - label: 'Location'
        name: 'location'
        widget: 'select'
        options:
          - 'Nationwide'
          - 'Multinational'
          - 'Alaska'
          - "Alabama"
          - "Arkansas"
          - "American Samoa"
          - "Arizona"
          - "California"
          - "Colorado"
          - "Connecticut"
          - "District of Columbia"
          - "Delaware"
          - "Florida"
          - "Georgia"
          - "Guam"
          - "Hawaii"
          - "Iowa"
          - "Idaho"
          - "Illinois"
          - "Indiana"
          - "Kansas"
          - "Kentucky"
          - "Louisiana"
          - "Massachusetts"
          - "Maryland"
          - "Maine"
          - "Michigan"
          - "Minnesota"
          - "Missouri"
          - "Mississippi"
          - "Montana"
          - "North Carolina"
          - "North Dakota"
          - "Nebraska"
          - "New Hampshire"
          - "New Jersey"
          - "New Mexico"
          - "Nevada"
          - "New York"
          - "Ohio"
          - "Oklahoma"
          - "Oregon"
          - "Pennsylvania"
          - "Puerto Rico"
          - "Rhode Island"
          - "South Carolina"
          - "South Dakota"
          - "Tennessee"
          - "Texas"
          - "Utah"
          - "Virginia"
          - "Virgin Islands"
          - "Vermont"
          - "Washington"
          - "Wisconsin"
          - "West Virginia"
          - "Wyoming"
      - { label: 'Coalition Member', name: 'is_member', widget: 'boolean', default: false}
      - { label: 'URL', name: 'site_url', widget: 'string', required: false}
      - label: "Logo"
        name: "logo"
        widget: "image"
        required: false
      - label: "Contact"
        name: "contact"
        widget: "object"
        fields: 
          - {label: "Name", name: "name", widget: "string", required: false}
          - {label: "Email", name: "email", widget: "string", required: false}
          - {label: "Phone", name: "phone", widget: "string", required: false}
        required: false
  - label: "Pages"
    name: "pages"
    editor:
      preview: false
    files:
      - label: "Home Page"
        name: "home"
        file: "pages/home.md"
        fields:
          - {label: 'Layout', name: 'layout', widget: 'hidden', default: 'default' }
          - {label: Intro, name: intro, widget: markdown}
          - label: Section
            name: section
            widget: list
            fields:
              - {label: Description, name: description, widget: markdown}
              - label: "Organizations"
                name: orgs
                widget: list
                fields:
                  - label: "Organization"
                    name: org
                    widget: relation
                    collection: organization
                    searchFields: ["name"]
                    valueField: name
                    displayFields: ["name"]
          - {label: Outro, name: outro, widget: markdown}
