backend:
  name: git-gateway
  branch: 'master'
media_folder: 'assets/uploads'
collections:
  - name: 'organization'
    label: 'Organization'
    folder: '_organizations/'
    create: true
    editor:
      preview: false
    identifier_field: 'name'
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'organization' }
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'markdown' }
      - label: 'Type'
        name: 'type'
        widget: 'select'
        multiple: true
        options:
          - { label: 'Connecting Need to Supply', value: 'CNS' }
          - { label: 'Sourcing New Supply', value: 'SNS' }
          - { label: 'Providing Data', value: 'PD' }
          - { label: 'Coordinating Financial Support', value: 'CFS' }
          - { label: 'Reprocessing PPE', value: 'RPPE' }
      - label: 'Location'
        name: 'location'
        widget: 'select'
        options:
          - 'Nationwide'
          - 'Multinational'
          - 'Alaska'
          - "Alabama"
          - "Arkansas"
          - "American Samoa"
          - "Arizona"
          - "California"
          - "Colorado"
          - "Connecticut"
          - "District of Columbia"
          - "Delaware"
          - "Florida"
          - "Georgia"
          - "Guam"
          - "Hawaii"
          - "Iowa"
          - "Idaho"
          - "Illinois"
          - "Indiana"
          - "Kansas"
          - "Kentucky"
          - "Louisiana"
          - "Massachusetts"
          - "Maryland"
          - "Maine"
          - "Michigan"
          - "Minnesota"
          - "Missouri"
          - "Mississippi"
          - "Montana"
          - "North Carolina"
          - "North Dakota"
          - "Nebraska"
          - "New Hampshire"
          - "New Jersey"
          - "New Mexico"
          - "Nevada"
          - "New York"
          - "Ohio"
          - "Oklahoma"
          - "Oregon"
          - "Pennsylvania"
          - "Puerto Rico"
          - "Rhode Island"
          - "South Carolina"
          - "South Dakota"
          - "Tennessee"
          - "Texas"
          - "Utah"
          - "Virginia"
          - "Virgin Islands"
          - "Vermont"
          - "Washington"
          - "Wisconsin"
          - "West Virginia"
          - "Wyoming"
      - { label: 'Coalition Member', name: 'is_member', widget: 'boolean', default: false}
      - { label: 'URL', name: 'site_url', widget: 'string', required: false}
      - label: "Logo"
        name: "logo"
        widget: "image"
        required: false
      - label: "Contact"
        name: "contact"
        widget: "object"
        fields: 
          - {label: "Name", name: "name", widget: "string", required: false}
          - {label: "Email", name: "email", widget: "string", required: false}
          - {label: "Phone", name: "phone", widget: "string", required: false}
        required: false
